# Generated by Django 3.2.6 on 2021-08-23 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aPropos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apropos',
            old_name='aPropos',
            new_name='A_propos',
        ),
    ]
