# Generated by Django 3.2.6 on 2021-08-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aPropos', '0002_rename_apropos_apropos_a_propos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apropos',
            name='Afficher',
        ),
    ]
