# Generated by Django 3.2.6 on 2021-08-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Partonaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=50)),
                ('Logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titre', models.CharField(max_length=50)),
                ('Video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Action', models.CharField(max_length=512)),
                ('Details', models.CharField(max_length=2048)),
                ('Date_Debut', models.DateField()),
                ('Date_Fin', models.DateField()),
                ('Atteint', models.FloatField()),
                ('Images', models.ManyToManyField(to='Actions.Images')),
                ('Partonaires', models.ManyToManyField(to='Actions.Partonaire')),
                ('Videos', models.ManyToManyField(to='Actions.Videos')),
            ],
        ),
    ]
