# Generated by Django 3.2.6 on 2021-08-23 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='Terminer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='actions',
            name='Date_Debut',
            field=models.DateTimeField(default=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='actions',
            name='Date_Fin',
            field=models.DateTimeField(),
        ),
    ]
