# Generated by Django 3.2.6 on 2021-08-23 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0002_auto_20210823_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='Date_Debut',
            field=models.DateField(default=datetime.datetime),
        ),
        migrations.AlterField(
            model_name='actions',
            name='Date_Fin',
            field=models.DateField(),
        ),
    ]
