# Generated by Django 3.2.6 on 2021-08-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0004_auto_20210823_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='Images',
            field=models.ManyToManyField(null=True, to='Actions.Images'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='Partonaires',
            field=models.ManyToManyField(null=True, to='Actions.Partonaire'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='Videos',
            field=models.ManyToManyField(null=True, to='Actions.Videos'),
        ),
    ]
