# Generated by Django 3.2.6 on 2021-08-23 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0006_auto_20210823_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='Partonaires',
            field=models.ManyToManyField(to='Actions.Partonaire'),
        ),
    ]
