# Generated by Django 3.2.6 on 2021-08-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0009_actions_objectif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='objectif',
            new_name='Objectif',
        ),
    ]
