# Generated by Django 3.2.6 on 2021-08-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0010_rename_objectif_actions_objectif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partonaire',
            name='Logo',
            field=models.ImageField(upload_to='Partonaire/'),
        ),
    ]
