# Generated by Django 3.2.6 on 2021-08-28 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0011_alter_partonaire_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=models.ImageField(upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='Video',
            field=models.FileField(upload_to='Videos/'),
        ),
    ]
