# Generated by Django 3.2.6 on 2021-08-28 15:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0015_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='partonaire',
            name='Logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Partonaire'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='Video',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='Videos'),
        ),
    ]
