# Generated by Django 3.2.6 on 2021-09-02 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0021_auto_20210902_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='Font',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Actions.fontimages'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='Images',
            field=models.ManyToManyField(blank=True, to='Actions.Images'),
        ),
    ]
