# Generated by Django 3.2.6 on 2021-09-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actions', '0022_auto_20210902_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='Activiter',
            field=models.CharField(default='Rien', max_length=4000),
        ),
    ]
